### ISSUE TITLE
def _build_variable_indices(band: np.ndarray) -> np.ndarray

### ISSUE THREAD

**Issue by Li-rr** [pmneila/PyMCubes#29]
Hi, I meet a problem, when i run in ubuntu16.04 python2.7.

>>> import numpy as np
>>> import mcubes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stu/.local/lib/python2.7/site-packages/mcubes/__init__.py", line 4, in <module>
    from .smoothing import *
  File "/home/stu/.local/lib/python2.7/site-packages/mcubes/smoothing.py", line 22
    def _build_variable_indices(band: np.ndarray) -> np.ndarray:
                                    ^
SyntaxError: invalid syntax

how can I fix this is?

**Comment by Li-rr** [comment]
I solve it ,thinks

**Comment by pmneila** [comment]
Hi @Li-rr,

Happy to hear that you solved it. Just for future reference for people that have the same problem, Python 2.7 is not supported anymore. That code should work properly with Python 3.7 or higher.
